theme: jekyll-theme-minimal
title: NeurIPS@Paris 2023 <br> <span style="color:grey"> 6<sup>th</sup> and 7<sup>th</sup> of December <br> Sorbonne Center for Artificial Intelligence (SCAI) </span>
description: ''
github:
  is_user_page: false
  is_project_page: false
logo: /docs/assets/photo_paris.jpg
